package com.octalsoftware.drewel.constant

object Tags {
    const val flag = "flag"
    const val deliver_to_customer = "deliver_to_customer"
    const val TEST = "test"
    const val pick_from_vendor = "pick_from_vendor"
    const val ERROR = "error"
    const val PREF = "pref"
    const val GCM = "GCM"
    const val GCMtoken = "GCMtoken"
    const val country_code = "country_code"
    const val USER_DATA = "userData"
    const val DATA = "data"
    const val LAT = "lat"
    const val LNG = "lng"
    const val auth_token = "auth_token"
    const val auth_key = "auth_key"
    const val primary_address = "primary_address"
    const val username = "username"
    const val vehicle_number = "vehicle_number"
    const val country = "country"
    const val location = "location"
    const val status = "status"
    const val exception = "exception"
    const val message = "message"
    const val FILE = "FILE"
    const val response = "response"
    const val modified = "modified"
    const val confirm_password = "confirm_password"
    const val is_available = "is_available"
    const val details = "details"
    const val old_password = "old_password"
    const val new_password = "new_password"
    const val first_name = "first_name"
    const val last_name = "last_name"
    const val email = "email"
    const val password = "password"
    const val device_type = "device_type"
    const val device_id = "device_id"
    const val address = "address"
    const val notification = "notification_orange"
    const val file = "file"
    const val type = "type"
    const val language = "language"
    const val time = "time"
    const val image = "image"
    const val created = "created"
    const val title = "title"
    const val user_id = "user_id"
    const val id = "id"
    const val name = "name"
    const val order_id = "order_id"
    const val description = "description"
    const val amount = "amount"
    const val items = "items"
    const val data = "data"
    const val notification_type = "notification_type"
    const val distance = "distance"
    const val device_token = "device_token"
    const val FCMtoken = "FCMtoken"
    const val msg = "msg"
    const val login = "login"
    const val latitude = "latitude"
    const val longitude = "longitude"
    const val code = "code"
    const val button: String = "button"
    const val ESTIMATE: String = "ESTIMATE"
    const val is_notification = "is_notification"
    const val payload = "payload"
    //    const  val API_LANGUAGE_ARABIC = "ara"
//    const  val API_LANGUAGE_ENGLISH = "eng"
    const val general = "general"
    const val LANGUAGE_ARABIC = "ar"
    const val LANGUAGE_ENGLISH = "en"
    const val LANGUAGE = "LANGUAGE"


    const val notification_id = "notification_id"
    const val second_user_id = "second_user_id"
    const val profile_image = "profile_image"
    const val item_id = "item_id"
    const val badge = "badge"
    const val FROM = "FROM"


}

